#!/bin/bash

function postinst() {
  get_answer "access"
  local access=$RET

  local user_string=""

  if [[ $access == "secret" ]]; then
    get_answer "user_string"
    user_string=$RET
  else
    user_string="STANDARD STRING"
  fi

  if [[ -z $DEBCONF_RECONFIGURE ]]; then
    echo "${user_string}" >> '{{ ENDPOINT_DIR }}/{{ PKG_NAME }}/mystring.txt'
  else
    echo "${user_string} (reconfigure)" >> '{{ ENDPOINT_DIR }}/{{ PKG_NAME }}/mystring.txt'
  fi
}

function config() {
  ask_question "greeting"
  local username=$RET

  set_window_title "Nice to meet you, ${username}!"

  ask_question "access"
  local answer=$RET
  set_window_title "Some testing: ${answer}"

  if [[ $answer == "secret" ]]; then
#    set_window_title "Advanced installation"
    ask_question "user_string"
  else
#    set_window_title "Standard installation"
    ask_question "deny"
  fi
}
