#!/bin/bash

#set -e # fail on any non-null exit code from command
#set -E # let shell functions inherit ERR trap

# including debconf commands
. /usr/share/debconf/confmodule

{{ API_SCRIPTS }}

{{ CUSTOM_SCRIPT }}

{{ CUSTOM_SCRIPT_CALL }}

exit 0
